### ISSUE TITLE
Feature Request: Allow multiple links in one Hyperlink field

### ISSUE THREAD

**Issue by aaronbushnell** [bencarr/statamic-hyperlink#11]
Every now and then a client wants to change a single Hyperlink field to a set of multiple. While it's possible to put a Hyperlink field into a Replicator it means you have to migrate _all_ the old links into this new fieldtype. Instead, it would be _great_ to have this capability baked-in so it can be easily enabled or disabled without requiring that migration.

**Comment by bencarr** [comment]
Just tagged `v2.0.0-beta.1` which adds multiple links in a single field! 

I’d love any feedback on the UI or the field configuration if you have a chance to check it out. I tried to keep it flexible for all the different ways I’ve run into this before, while keeping the defaults exactly like V1 to avoid any data migration. 

There’s a small [Upgrade Guide](https://github.com/bencarr/statamic-hyperlink/blob/v2.0.0-beta.1/README.md#upgrade-guide) in the README, but the gist is there’s 2 new config options for `min_items` and `max_items`, which default to `0` and `1`. Bumping up `max_items` adds a new “Add Link” button at the bottom of the field, and once there’s more than one link in a field you get some extra controls to reorder or delete the individual links.

For your original scenario, in V2 if you update the configuration on an existing field to support multiple links, you won’t need a data migration (the data will just be updated next time the entry is saved), you’ll just need to update your templates to expect an array of links.

**Comment by aaronbushnell** [comment]
This is **_excellent_**, @bencarr! Really makes the experience super nice to not have to migrate if the client wants additional links. Great work!

**Comment by bencarr** [comment]
🎉 2.0 is out now with multiple links in a single field!

**Comment by aaronbushnell** [comment]
Awesome work, @bencarr! Congrats! 🥳
