### ISSUE TITLE
[Feature Request] Allow link text to be inferred but overwritten

### ISSUE THREAD

**Issue by aaronbushnell** [bencarr/statamic-hyperlink#15]
I realize this might be a tall order and I'd be willing to help with a pull request for this one!

I'd love if the "Link Text" field was optional and. by default, this text was automatically supplied by the link itself. Here's a couple examples:

![Screenshot 2024-04-11 at 4 47 11 PM](https://github.com/bencarr/statamic-hyperlink/assets/315202/601c8adc-148d-45b7-8d74-d1cc8ade6013)

This would save content authors a bit of time where the link and the link text should be the same, but also allow it to be overwritten when necessary.

This would be backwards-compatible with the current setup because the text in the "Link Text" field is used, no matter what the selected link is.

**Comment by aaronbushnell** [comment]
Took a stab at this one and stubbed out some tests for it!

**Comment by bencarr** [comment]
[v3.0.0](https://github.com/bencarr/statamic-hyperlink/releases/tag/v3.0.0) is out now with Statamic 5 support and optional link text!

**Comment by aaronbushnell** [comment]
![giphy](https://github.com/bencarr/statamic-hyperlink/assets/315202/7b1559b8-8707-4178-8204-fe2c16c615b5)
