### ISSUE TITLE
Dark mode background on multiple links

### ISSUE THREAD

**Issue by aaronbushnell** [bencarr/statamic-hyperlink#19]
Hey Ben—I saw you pushed out a dark mode update but I'm not sure the CSS got compiled with that change! Here's what I'm seeing on my end (happy to throw ya a PR if you're tied up!)

<img width="878" alt="Screenshot 2024-05-21 at 6 27 25 PM" src="https://github.com/bencarr/statamic-hyperlink/assets/315202/26e56e9f-3b92-47d0-9cf4-dfa09754cc0a">

**Comment by bencarr** [comment]
Well that was odd! [`v3.0.2`](https://github.com/bencarr/statamic-hyperlink/releases/tag/v3.0.2) is out now with this fix. The CSS should all get compiled as part of the release action, but it most certainly did not. Thanks for flagging!

**Comment by aaronbushnell** [comment]
That did it, thanks so much!
