### ISSUE TITLE
Changing field back to "None" and saving does not empty out the link data

### ISSUE THREAD

**Issue by aaronbushnell** [bencarr/statamic-hyperlink#20]
We have a Hyperlink field that can't be set from a value back to "None" without manually updating the YAML file. Here's how to recreate this issue:

1. Add a Hyperlink field to a blueprint and create a new entry
2. Set the field to "URL" and fill out some dummy content
3. Save the entry and refresh
4. Change the URL field to the "None" option
5. Save and refresh
6. The field shows the old value and "None" has not emptied out the field in the YAML file

**Comment by bencarr** [comment]
Thanks, @aaronbushnell! [`v3.0.3`](https://github.com/bencarr/statamic-hyperlink/releases/tag/v3.0.3) is out now with a fix for this issue.

**Comment by aaronbushnell** [comment]
Thanks so much, @bencarr!
