### ISSUE TITLE
Issues selecting link type when used in a nested replicator

### ISSUE THREAD

**Issue by aaronbushnell** [bencarr/statamic-hyperlink#22]
I'm seeing some oddities with the Hyperlink field and I _think_ it might be when it's used in a nested replicator? I can share my site content if necessary for this one!

https://github.com/bencarr/statamic-hyperlink/assets/315202/5b10c11b-abbf-43a9-ac9c-5d591af54142

**Comment by bencarr** [comment]
Hmm, any console errors that might lend some insight? And which version of Statamic? 

Did a quick test locally and I'm not seeing an issue in a Replicator → Replicator → Hyperlink field setup, but might be something more specific than that.

**Comment by aaronbushnell** [comment]
Hey @bencarr, this is the latest version of Statamic (5.11) but there's no console errors or logs that seem to be cropping up with this!

Here's when I see it:
- Create a new entry with values set for the Hyperlink fields in a nested Replicator
- Refresh the entry
- Try to change the Hyperlink type to something else

Happy to send you anything that might help with debugging!

**Comment by bencarr** [comment]
Can you drop me your `composer.json`? I'm wondering if it's a conflict with another addon

**Comment by aaronbushnell** [comment]
Ah, you know what, @bencarr — I think I'm closer to the root cause on this one. I tried pairing down my composer.json to just your addon and Statamic but had no luck.

What does seem to be related though is we have our Replicator blocks (and the nested ones) to be collapsed by default. Disabling that fixes this! Does the collapsed behavior prevent this from working?

**Comment by bencarr** [comment]
Good catch! Certainly not intentional. Let me take a closer look now that I can reproduce it.

**Comment by bencarr** [comment]
[v3.0.4](https://github.com/bencarr/statamic-hyperlink/releases/tag/v3.0.4) is out now with a fix for this issue!

**Comment by aaronbushnell** [comment]
Thanks so much, @bencarr!
