### ISSUE TITLE
Error while install

### ISSUE THREAD

**Issue by yaser2490** [bencarr/statamic-hyperlink#4]
INFO  Publishing [statamic-hyperlink] assets.

   ERROR  Can't locate path: <C:\Work\projects\laravel\StataBit\vendor\bencarr\statamic-hyperlink\src/../dist/js/addon.js>.

![Screenshot 2023-03-18 112408](https://user-images.githubusercontent.com/70744366/226092992-293cdeb7-44c4-4d7a-b49e-6609da6f94da.png)

**Comment by bencarr** [comment]
Hi Yaser! Sorry for the trouble. I just released [v1.1.1](https://github.com/bencarr/statamic-hyperlink/tree/v1.1.1) with a fix for this issue on new installs.
