### ISSUE TITLE
I can not get the address of the term !

### ISSUE THREAD

**Issue by yaser2490** [bencarr/statamic-hyperlink#6]
in  +url: "term::product-categories::digitals" i can not get the address.

How should I get the full address?
I am in Blade page.

The addresses of the entries are correct
But there is this problem in term!

BenCarr\Hyperlink\Helpers\HyperlinkData {#2396 ▼ // app\Http\Controllers\PageController.php:23
  +url: "term::product-categories::digitals"
  +target: "_blank"
  +email: null
  +phone: null
  +entry: null
  +asset: null
  +term: Statamic\Taxonomies\LocalizedTerm {#2372 ▶}
  #attributes: Illuminate\View\ComponentAttributeBag {#2398 ▶}
  +type: "term"
  +link: "term::product-categories::digitals"
  +text: "#"
  +newWindow: true

**Comment by bencarr** [comment]
Hi Yaser! Thanks for reporting. I just released [v1.1.2](https://github.com/bencarr/statamic-hyperlink/tree/v1.1.2) with a fix for the term URLs. 

Terms in most of my Statamic sites have been collection-specific, so I got used to generating collection-specific URLs manually. I added a note to the README about collection-specific term URLs, and fixed the behavior so Term links now properly point to the global term URL.
