### ISSUE TITLE
Css error

### ISSUE THREAD

**Issue by yaser2490** [bencarr/statamic-hyperlink#9]
Hi
**How i can fix it?**

![2023-06-24](https://github.com/bencarr/statamic-hyperlink/assets/70744366/0d9c3b87-497d-4a59-9c2e-eae3fdb04f36)

**Comment by bencarr** [comment]
Hi Yaser! I just released [v1.2.3](https://github.com/bencarr/statamic-hyperlink/releases/tag/v1.2.3) with a fix for the overlap. 

Thank you for the very clear screenshot! It was helpful to help diagnose the problem.
